[package]
name = "oxc_checker"
version = "0.1.0"
edition = "2024"

[features]
default = []
conformance = []
conformance-tsc = []

[dependencies]
oxc_ast = "0.132.0"
oxc_ast_visit = "0.132.0"
oxc_allocator =  "0.132.0"
oxc_parser =  "0.132.0"
oxc_resolver = "11.19.1"
oxc_semantic = { version = "0.132.0", features = ["cfg"] }
oxc_span =  "0.132.0"
oxc_syntax = "0.132.0"
oxc_index = "4.1.0"
oxc_str = "0.132.0"
